### ISSUE TITLE
Data download unsuccessful

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#239]
Tested both prod and dev repositories
It seems like i need to login to download the file of public record
e.g. https://repository.data.auscope.org.au/dataset/cloncurry-metal-multimodal-integrated-mineral-system-characterisation-data

downloaded file - https://repository.data.auscope.org.au/dataset/eda39b66-11ed-490b-9aa6-21f5653bf27f/resource/80708bde-702f-4af9-871b-06354dfaeb63/download/readme.txt
<img width="1285" alt="Screenshot 2024-06-19 at 7 46 38 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/a3169342-1fde-49b0-a8cd-0109ea94c32d">

if i login as a member, editor or admin, i can download the public record.

**Comment by stuartwoodman** [comment]
Not sure how this ever worked, digging through the ckan code-base the error was thrown from the Resource read method when it calls the package_show action. Because the package_show wasn't annotated with the auth_allow_anonymous_access annotation, anonymous users couldn't access and a 403 would be thrown. With the annotation and a few extra checks to deny anonymous users if the package is not private, everything seems to be working again.

**Comment by kitchenprinzessin3880** [comment]
tested prod and dev repositories. can download file from existing data and new record created
