### ISSUE TITLE
Update admin profile information

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [AuScope/ckan-docker#61]
Check admin details at [repo-url] /user/edit/ckan_admin
The following are included in the ckan_admin details:
Full Name - AuScope Admin
Email - auscope.doi@csiro.au

**Comment by bmotevalli** [comment]
done.

**Comment by kitchenprinzessin3880** [comment]
@bmotevalli tested https://repository-dev.data.auscope.org.au/dataset/
seems like the issue has not been resolved, it still point to stuart details, see below

<img width="950" alt="Screenshot 2024-03-18 at 4 04 06 PM" src="https://github.com/AuScope/ckan-docker/assets/11935313/09cc2817-7dfa-44f4-8ad0-2c83b74497ed">

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 , the ENV VARS are updated, please see below:

![env_vars](https://github.com/AuScope/ckan-docker/assets/28551953/30042871-412c-487f-9af6-5ff957bbfaa4)

Probably, the Admin Account is created on the first time initialization of the CKAN app. It might be that it is needed to be changed/updated within the database rather than simply via the ENV VARS. If that's the case, it would probably be better @stuartwoodman will have a look as he would have a better idea where we need to update this.

**Comment by kitchenprinzessin3880** [comment]
@bmotevalli thanks for the clarification. i will assign the issue to @stuartwoodman 
btw, I can update the details via UI, but I don't want to do it every time we do a release (it should be populated as part of the deployment).

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 actually, I guess the safest way to update the admin account is through the UI. I just logged in with the admin account, the Profile can be editted. Probably, if we do this via the UI, CKAN will take care of all locations that an update is required. I guess it would be safer than we manually attempt to update the Database. Would you want I proceed updating it?

**Comment by bmotevalli** [comment]
@kitchenprinzessin3880 I just updated the admin account via UI. It should be fine now. Please re-test.

**Comment by kitchenprinzessin3880** [comment]
@stuartwoodman can we close this issue? If there is another release, do we need to update it again via UI? please confirm..

**Comment by stuartwoodman** [comment]
Should be fine to close, the issue was the system being initialized with the old values, Ben has updated the Vault so if it were to create a new version it should use those instead.

**Comment by kitchenprinzessin3880** [comment]
ok thanks all..
